export { copywriting } from '@/config/copywriting';
export {
  countWords,
  countChars,
  validateWordCount,
  validateCharCount,
  allValid,
  summarizeValidation,
} from '@/lib/copywriting/count';
export {
  validateHeadingLength,
  validateMetaDescriptionLength,
  validateCtaLength,
  validateHeroWordCount,
  validateFaqAnswerLength,
  validateSectionIntro,
  validateFeatureCopy,
  validateBenefitCopy,
  validateHeroCopy,
  validateFaqCopy,
  validateArticleCopy,
  isCopyValid,
  type PageCopyContext,
} from '@/lib/copywriting/validate';
export {
  toCtaProps,
  toRequiredCtaProps,
  toHeroCopy,
  heroCopyToProps,
  toSectionCopy,
  sectionCopyToProps,
  toFaqContent,
  faqContentToProps,
  toFeatureContent,
  featureContentToProps,
  toBenefitContent,
  benefitContentToProps,
  toTestimonialContent,
  testimonialContentToProps,
  toArticleContent,
  finalCtaCopyToProps,
} from '@/lib/copywriting/adapters';
