export { Faq } from '@/components/sections/faq';
export { FaqPageView } from '@/components/sections/FaqPageView';
export { PagePlaceholder } from '@/components/sections/PagePlaceholder';
export { EmptySection } from '@/components/sections/EmptySection';
export { ServicePageView } from '@/components/sections/ServicePageView';
export { HomePageView } from '@/components/sections/HomePageView';
export { AboutPageView } from '@/components/sections/AboutPageView';
export { ContactPageView } from '@/components/sections/ContactPageView';
export { PrivacyPolicyPageView } from '@/components/sections/PrivacyPolicyPageView';
export { TermsAndConditionsPageView } from '@/components/sections/TermsAndConditionsPageView';
export { RefundPolicyPageView } from '@/components/sections/RefundPolicyPageView';
export { CookiePolicyPageView } from '@/components/sections/CookiePolicyPageView';
export { DisclaimerPageView } from '@/components/sections/DisclaimerPageView';
export { TrustCenter } from '@/components/sections/TrustCenter';
export { LegalTableOfContents } from '@/components/sections/legal/LegalTableOfContents';
export { LegalPolicyPageView } from '@/components/sections/legal/LegalPolicyPageView';
export { LearnArticleView } from '@/components/sections/LearnArticleView';
export * from '@/components/sections/service';
export * from '@/components/sections/learn';
